DROP TABLE HGI;
CREATE EXTERNAL TABLE HGI (PROVIDERID STRING, HOSPITALNAME STRING, ADDRESS STRING, CITY STRING, STATE STRING, ZIP STRING, COUNTY STRING, PHONE STRING, HOSPITALTYPE STRING, HOSPITALOWNERSHIP STRING, EMERGENCYSERVICES STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE LOCATION '/data/w205tables';

DROP TABLE TECH;
CREATE EXTERNAL TABLE TECH (PROVIDERID STRING, HOSPITALNAME STRING, ADDRESS STRING, CITY STRING, STATE STRING, ZIP STRING, COUNTY STRING, PHONE STRING, CONDITION STRING, MEASUREID STRING, MEASURENAME STRING, SCORE STRING, SAMPLE STRING, FOOTNOTE STRING, MEASURESTART STRING, MEASUREEND STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE LOCATION '/data/w205tables';

DROP TABLE TECS;
CREATE EXTERNAL TABLE TECS (STATE STRING, CONDITION STRING, MEASURENAME STRING, MEASUREID STRING, SCORE STRING, FOOTNOTE STRING, MEASURESTART STRING, MEASUREEND STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE LOCATION '/data/w205tables';

DROP TABLE TECN;
CREATE EXTERNAL TABLE TECN (MEASURENAME STRING, MEASUREID STRING, CONDITION STRING, CATEGORY STRING, SCORE STRING, FOOTNOTE STRING, MEASURESTART STRING, MEASUREEND STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE LOCATION '/data/w205tables';

DROP TABLE MD;
CREATE EXTERNAL TABLE MD (MEASURENAME STRING, MEASUREID STRING, MEASURESTARTQ STRING, MEASURESTART STRING, MEASUREENDQ STRING, MEASUREEND STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE LOCATION '/data/w205tables';

DROP TABLE RDN;
CREATE EXTERNAL TABLE RDN (MEASURENAME STRING, MEASUREID STRING, NATIONALRATE STRING, NUMHOSPWORSE STRING, NUMHOSPSAME STRING, NUMHOSPBETTER STRING, NUMHOSPTOOFEW STRING, FOOTNOTE STRING, MEASUREDSTART STRING, MEASUREEND STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE LOCATION '/data/w205tables';

DROP TABLE RDS;
CREATE EXTERNAL TABLE RDS (STATE STRING, MEASURENAME STRING, MEASUREID STRING, NUMHOSPWORSE INT, NUMHOSPSAME INT, NUMHOSPBETTER INT, NUMHOSPTOOFEW INT,FOOTNOTE STRING, MEASUREDSTART STRING, MEASUREEND STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE LOCATION '/data/w205tables';

DROP TABLE RDH;
CREATE EXTERNAL TABLE RDH (PROVIDERID STRING, HOSPITALNAME STRING, ADDRESS STRING, CITY STRING, STATE STRING, ZIP STRING, COUNTY STRING, PHONE STRING, MEASURENAME STRING, MEASUREID STRING, COMPARETONATIONAL STRING, DENOMINATOR STRING, SCORE STRING, LOWEREST STRING, HIGHEREST STRING, FOOTNOTE STRING, MEASURESTART STRING, MEASUREEND STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE LOCATION '/data/w205tables';

DROP TABLE SURVEY;
CREATE EXTERNAL TABLE SURVEY (PROVIDERID STRING, HOSPITALNAME STRING, ADDRESS STRING, CITY STRING, STATE STRING, ZIP STRING, COUNTY STRING, COMMNURSEACHIEVE STRING, COMMNURSEIMPROVE STRING, COMMNURSEDIM STRING, COMMDOCACHIEVE STRING, COMMDOCIMPROVE STRING, COMMDOCDIM STRING, RESPONSIVENESSSTAFFACHIEVE STRING, RESPONSIVENESSSTAFFIMPROVE STRING, RESPONSIVENESSSTAFFDIM STRING, PAINMGMTACHIEVE STRING, PAINMGMTIMPROVE STRING, PAINMGMTDIM STRING, COMMMEDICINEACHIEVE STRING, COMMMEDICINEIMPROVE STRING, COMMMEDICINEDIM STRING, CLEANQUIETACHIEVE STRING, CLEANQUIETIMPROVE STRING, CLEANQUIETDIM STRING, DISCHARGEACHIEVE STRING, DISCHARGEIMPROVE STRING, DISCHARGEDIM STRING, OVERALLACHIEVE STRING, OVERALLIMPROVE STRING, OVERALLDIM STRING, HCAHPSBASE STRING, HCAHPSCONSISTENCY STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE LOCATION '/data/w205tables';

LOAD DATA INPATH '/user/rbarrera/hospital_compare/HGI.csv' OVERWRITE INTO TABLE HGI;
LOAD DATA INPATH '/user/rbarrera/hospital_compare/RDH.csv' OVERWRITE INTO TABLE RDH;
LOAD DATA INPATH '/user/rbarrera/hospital_compare/RDS.csv' OVERWRITE INTO TABLE RDS;
LOAD DATA INPATH '/user/rbarrera/hospital_compare/RDN.csv' OVERWRITE INTO TABLE RDN;
LOAD DATA INPATH '/user/rbarrera/hospital_compare/TECN.csv' OVERWRITE INTO TABLE TECN;
LOAD DATA INPATH '/user/rbarrera/hospital_compare/TECH.csv' OVERWRITE INTO TABLE TECH;
LOAD DATA INPATH '/user/rbarrera/hospital_compare/TECS.csv' OVERWRITE INTO TABLE TECS;
LOAD DATA INPATH '/user/rbarrera/hospital_compare/survey.csv' OVERWRITE INTO TABLE SURVEY;
LOAD DATA INPATH '/user/rbarrera/hospital_compare/MD.csv' OVERWRITE INTO TABLE MD;